spring:
  profiles:
    active: dev


logging:
  level:
    root: WARN
    com:
      fastjrun:
        ddns: DEBUG
    org:
      springframework:
        boot: WARN
ddns:
  aliyun:
    accessKeyId: hello
    accessKeySecret: secret
  checkIPTask:
    configDomain: fastjrun.com
    rR: test
    cron: 0 * * * * ?


