spring:
  profiles:
    active: dev


logging:
  level:
    root: WARN
    com:
      fastjrun:
        ddns: DEBUG
    org:
      springframework:
        boot: WARN
ddns:
  locateIPUrl: "http://ip.cuiyingfeng.com"
  aliyun:
    accessKeyId: xxx
    accessKeySecret: yyy
  checkIPTask:
    configDomain: pi4k8s.cn
    rR: test
    cron: 0 * * * * ?


