spring:
  profiles:
    active: dev

mybatis:
  configuration:
    log-impl: "org.apache.ibatis.logging.stdout.StdOutImpl"
logging:
  level:
    root: WARN
    com:
      fastjrun:
        ddns: DEBUG
    org:
      springframework:
        boot: WARN
